//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDerivativeCaculator")]
public interface IDerivativeCaculator
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDerivativeCaculator/CaculateDerivative", ReplyAction="http://tempuri.org/IDerivativeCaculator/CaculateDerivativeResponse")]
    decimal CaculateDerivative(string[] symbols, decimal[] parametors, string[] functions);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDerivativeCaculatorChannel : IDerivativeCaculator, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DerivativeCaculatorClient : System.ServiceModel.ClientBase<IDerivativeCaculator>, IDerivativeCaculator
{
    
    public DerivativeCaculatorClient()
    {
    }
    
    public DerivativeCaculatorClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DerivativeCaculatorClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DerivativeCaculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DerivativeCaculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public decimal CaculateDerivative(string[] symbols, decimal[] parametors, string[] functions)
    {
        return base.Channel.CaculateDerivative(symbols, parametors, functions);
    }
}
